config:
  address: ""
  logLevel: "info"
  role: ""
  secretsPath: ""
  storagePath: ""
  storageCredentialsKey: ""
  storageCredentialsSecret: ""
deployment:
  image:
    tag: ""
  resources: {}
serviceAccount:
  name: ""
