apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gateway-controller.fullname" . }}
  labels:
  {{- include "gateway-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "gateway-controller.fullname" . }}'
subjects:
- kind: ServiceAccount
  name: '{{ include "gateway-controller.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
