apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway-controller.name" . }}
rules:
{{- $rbac := .Files.Get "generated/rbac.yaml" | fromYaml -}}
{{- get $rbac "rules" | toYaml | nindent 2 -}}
