name: publish

on:
  push:
    branches:
      - "*"

jobs:
  release:
    concurrency:
      group: release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: set up qemu
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.5"
      - name: log in to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install tools
        run: |
          sudo BIN=/usr/local/bin make install-tools
      - name: generate content
        run: |
          make generate
          git diff --exit-code
      - name: determine version
        id: version
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_NAME="$(echo "${BRANCH_NAME}" | sed 's/[^a-zA-Z0-9.-]/-/g')"
          if [[ "${BRANCH_NAME}" == "dev" ]]; then
            VERSION="$(svu next --prerelease "rc.${GITHUB_RUN_NUMBER}")"
          elif [[ "${BRANCH_NAME}" == "main" ]]; then
            VERSION="$(svu next)"
          else
            VERSION="$(svu next --prerelease "alpha.${GITHUB_RUN_NUMBER}" --metadata "${BRANCH_NAME}")"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: create git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "${{ steps.version.outputs.version }}"
          git push origin "${{ steps.version.outputs.version }}"
      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: "2.12.7"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: package helm chart
        run: |
          go run ./scripts/set-helm-version ./charts/gateway-controller "${{ steps.version.outputs.version }}"
          helm package ./charts/gateway-controller
      - name: update release with helm chart
        uses: softprops/action-gh-release@v2
        with:
          files: |
            gateway-controller-v${{ steps.version.outputs.version }}.tgz
          tag_name: "v${{ steps.version.outputs.version }}"
      - name: run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_RELEASE_NAME_TEMPLATE: "{{ .Version }}"
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
