apiVersion: v2
name: gateway-controller
description: A helm chart that deploys the gateway controller - used to dynamically update Gateway resources with hostnames from attached routes.
type: application
version: 0.0.0
appVersion: "0.0.0"
