apiVersion: v2
name: gateway-controller
description: A helm chart that deploys a gateway controller used to dynamically update gateway resources with hostnames from attached routes.
type: application
version: 0.0.0
appVersion: "0.0.0"
