gatewayController:
  gatewayController:
    args:
    - homelab-helper
    - gateway-run-controller
    image:
      repository: ghcr.io/benfiola/homelab-helper
      tag: 0.6.21
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
imagePullSecrets: []
kubernetesClusterDomain: cluster.local
