gatewayController:
  args:
    - homelab-helper
    - gateway-run-controller
  image:
    repository: ghcr.io/benfiola/homelab-helper
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []

imagePullSecrets: []
kubernetesClusterDomain: cluster.local
